EVENTS_REDIS_DATABASE_PASSWORD = None
EVENTS_REDIS_DATABASE_HOST = "localhost"
EVENTS_REDIS_DATABASE_PORT = 6379
EVENTS_REDIS_DATABASE_DB = 7
STOMP_HOST_AND_PORTS = [('127.0.0.1', 61613)]
STOMP_SERVER_PASSWORD = 'password'
STOMP_SERVER_USER = 'admin'
STOMP_HEARTBEATS = (4000, 4000)
