EVENTS_REDIS_DATABASE_PASSWORD = None
EVENTS_REDIS_DATABASE_HOST = "localhost"
EVENTS_REDIS_DATABASE_PORT = 6379
EVENTS_REDIS_DATABASE_DB = 7
STOMP_HOST_AND_PORTS = [('127.0.0.1', 61613)]
STOMP_SERVER_PASSWORD = 'password'
STOMP_SERVER_USER = 'admin'
STOMP_HEARTBEATS = (4000, 4000)

AEROSPIKE_HOSTS = [('127.0.0.1', 3000)]
AEROSPIKE_WRITE_POLICIES = {'total_timeout': 2000, 'max_retries': 0}
AEROSPIKE_READ_POLICIES = {'total_timeout': 1500, 'max_retries': 1}
REDIS_DATABASE_DB = 11
REDIS_DATABASE_HOST = '127.0.0.1'
REDIS_DATABASE_PORT = 6379
REDIS_DATABASE_PASSWORD = None
AEROSPIKE_SET_MODULE_NAME = 'set'
AEROSPIKE_DEFAULT_SET_NAME = 'set'
AEROSPIKE_DEFAULT_NAMESPACE = 'test'

GLOBAL_CACHE_REDIS_DATABASE_PASSWORD = None
GLOBAL_CACHE_REDIS_DATABASE_HOST = "localhost"
GLOBAL_CACHE_REDIS_DATABASE_PORT = 6379
GLOBAL_CACHE_REDIS_DATABASE_DB = 7
